# Generated by Django 6.0.1 on 2026-01-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbUser',
            fields=[
                ('id_user', models.AutoField(db_column='id_user', primary_key=True, serialize=False)),
                ('nama', models.CharField(blank=True, db_column='nama', max_length=100, null=True)),
                ('username', models.CharField(db_column='username', db_index=True, max_length=50, unique=True)),
                ('password', models.CharField(db_column='password', max_length=255)),
                ('role', models.CharField(blank=True, choices=[('pemilik', 'Pemilik'), ('kasir', 'Kasir')], db_column='role', max_length=30, null=True)),
                ('status', models.CharField(blank=True, choices=[('aktif', 'Aktif'), ('nonaktif', 'Nonaktif')], db_column='status', max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='created_at', null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_column='updated_at', null=True)),
            ],
            options={
                'db_table': 'tb_user',
                'managed': False,
            },
        ),
    ]
